#!/bin/bash
#python setup.py install --prefix=$prefix

usage()
{
cat << EOF
SLV installation script

usage: $0 options

OPTIONS:
   -h      Show this message
   -p      prefix (default /usr/local)
   -x      exec_prefix (default /usr/local)
   -v      Verbose

NOTES:
   if only prefix chosen, the exec_prefix will be the same as prefix
EOF
}

# installation variables
PREFIX=
EXEC_PREFIX=
VERBOSE=

# gather options
while getopts “hp:x:v” OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         p)
             PREFIX=$OPTARG
             ;;
         x)
             EXEC_PREFIX=$OPTARG
             ;;
         v)
             VERBOSE=1
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

# if prefix is not set, set it to /usr/local
if [[ -z $PREFIX ]]
then
     EXEC_PREFIX=/usr/local
fi

# if exec-prefix is not set, set it up the same as prefix
if [[ -z $EXEC_PREFIX ]]
then
     EXEC_PREFIX=$PREFIX
fi

if [[ -z $PREFIX ]] || [[ -z $EXEC_PREFIX ]]
then
     echo Nothing to do. Run with -h option
     exit 1
fi

# install LIBBBG
python setup.py install --prefix=$PREFIX --exec-prefix=$EXEC_PREFIX

# copy the shared libraries
export SLV_LIB=$PREFIX/lib/python2.7/dist-packages

echo Copying shared libraries
#cp -v $SLV_LIB/shftce.so ./solvshift
#cp -v $SLV_LIB/shftex.so ./solvshift
#cp -v $SLV_LIB/efprot.so ./solvshift
#cp -v $SLV_LIB/exrep.so ./solvshift

# install solpol and solpol2 extensions - requires mathematical libraries linked to NumPy!
cd solvshift/src
f2py -c --quiet --link-lapack_opt --link-blas_opt -m solpol  solpol.f
f2py -c --quiet --link-lapack_opt --link-blas_opt -m solpol2 solpol2.f
mv -v $PWD/solpol.so $PWD/solpol2.so $SLV_LIB/solvshift
cd ../..

echo --- INFO ---------------------------------------------------------------------------
echo
echo Modify your $HOME/.bashrc script adding the following lines:
echo
echo export PYTHONPATH=$SLV_LIB:$PYTHONPATH
echo export SLV_DATA=$SLV_LIB/solvshift-dat
echo
echo Then, type in the terminal
echo
echo source $HOME/.bashrc
echo
echo ------------------------------------------------------------------------------------

