#!/bin/bash

# ----------------------------------------------------------- #
#                SOLVSHIFT CONFIGURATION FILE                 # 
# ----------------------------------------------------------- #

# set here your path of SLV package
export SLV_PATH='/home/globula/programs/solvshift'

# set here the path for COULOMB.py package if wanted
export COULOMB_PATH='/home/globula/programs/coulomb/'
# set this variable as '1' if you want to use coulomb package
export __IMPORT__COULOMB__=1
# set this variable as '1' if you want to use Easyvis
export __IMPORT_EASYVIZ__=1
# target directory with solute-solvent files
export TARGET_DIR=$PWD/../../target

# execute SLV!
python $SLV_PATH/solvshift/runsolvshft.py ${*}

# good luck! 
#           @Globulion

