#!/bin/bash

# ----------------------------------------------------------------- #
#                   SOLVSHIFT CONFIGURATION FILE                    # 
# ----------------------------------------------------------------- #

#    Copyright © 2012, Bartosz Błasiak (blasiak.bartosz@gmail.com)
#  
#    This program is free software; you can redistribute it and/or 
#    modify it under the terms of the GNU General Public License 
#    as published by the Free Software Foundation; either version 2 
#    of the License, or (at your option) any later version.
# 
#    This program is distributed in the hope that it will be useful, 
#    but WITHOUT ANY WARRANTY; without even the implied warranty of 
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
#    See the GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License 
#    along with this program; if not, write to the Free Software 
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.


# set here your path of SLV package
export SLV_PATH='/home/globula/programs/solvshift/'

# set here the path for COULOMB.py package if wanted
export COULOMB_PATH='/home/globula/programs/clmb-master/'

# set this variable as '1' if you want to use coulomb package
export __IMPORT__COULOMB__=1

# set this variable as '1' if you want to use Easyvis
export __IMPORT_EASYVIZ__=1

# set this variable as '1' if you want to use MDAnalysis
export __IMPORT_MDANALYSIS__=1

# target directory with solute-solvent files
export TARGET_DIR=$PWD/../../target

# execute SLV!
python $SLV_PATH/solvshift/runsolvshft.py ${*}

# good luck! 
#           @Globulion

