#!/bin/bash
echo Convert eps to eps with reduction of size but maintaining quality as much as possible
file=$1
cp -v $file y.eps
epstopdf --res=600 --noembed y.eps
pdftops -eps y.pdf u.eps
rm -v y.pdf y.eps
echo Size of "< u.eps >" file
du -hs u.eps
echo Check file "< u.eps >"

