#!/usr/bin/python
"""
 Calculate averages from report MD
 Usage: [report] [ncol]
"""
print __doc__
from sys import argv, exit
if len(argv)==1:exit()
from numpy import average, std
from scitools import filetable as ft

# read the data
f = open(argv[1])
ncol = int(argv[2])
r = ft.read(f)
f.close()

# choose the column
k = r[:,ncol-1]
a = average(k)
s = std(k)

# print the output
print "\n%15.3f +/- %15.3f\n" % (a,s)

