#!/usr/bin/python
"""
Shows the FRG file

Usage:
  ./show.py frg_file
"""
print __doc__
from sys import argv,exit
if len(argv)==1:exit()
from solvshift.slvpar import Frag
from units import UNITS as u

# read options
cunit=False
if '-u' in argv: cunit=True

# read frg file
a = Frag(argv[1])
par = a.get()

# print LMOC
lmoc = par['lmoc'] 
if cunit: lmoc *= u.BohrToAngstrom

print " LMO Centrioids:\n"
for i in lmoc:
    print " %10.4f %10.4f %10.4f" % tuple(i)
print
