#!/usr/bin/python
"""
Pick the solute-solvent clusters from MD trajectory file

Usage:

 [xtc] nframes dframe thr name_1 n_1 a_c <name_2> <n_2> <a_s>

Notes: 
 - nframes - number of frames
 - dframe  - frame increment
 - thr     - threshold for cluster size (COG-COG max distance)
            (in Angstroms)
 - name_1/2- name of molecule 
 - n_1/n_2 - number of solute/solvent atoms
 - s_1/s_2 - list of atoms (delimiter: coma ,)
             ex. C,H,O,O,N,H,H,H,H
 - Defaults are for water molecule (O,H,H)
"""
from sys import argv, exit
from math import sqrt as msqrt
from string import Template
print __doc__
if len(argv)==1:exit()
from numpy import float32, zeros, array, sum, sqrt, where, lexsort, arange
from MDAnalysis.coordinates.xdrfile.libxdrfile2 import xdrfile_open, xdrfile_close,\
                                                       read_xtc_natoms, read_xtc  ,\
                                                       read_xtc, DIM, exdrOK
from MDAnalysis.coordinates.TRJ import TRJReader, NCDFReader
from units import UNITS as u
import glob, os

# GAMESS input template
t_c = """\
 $system mwords=5 memddi=12 parall=.t. $end
 $contrl scftyp=rhf runtyp=optimize icharg=0 mult=1 units=angs
         maxit=100 exetyp=run ispher=-1 coord=fragonly
         icut=20 itol=30 local=pop $end
!$globop rndini=.true. riord=rand mcmin=.true.
!        mctyp=4 nblock=0 $end
!$statpt nstep=20 $end
!$basis  gbasis=newnew extfil=.true. $end
 $efrag
coord=cart iscrelect=1 iscrpol=1
FRAGNAME=@SOLUTE
@COORD\
@SCOORD\
 $end
 $@SOLUTE
@PARC\
 $end
 $@SOLVENT
@PARS\
 $end
"""
t_s = """\
FRAGNAME=@SOLVENT
@COORD"""

# operational arguments
trajectory =     argv[1]
nframes    =   int(argv[2])
dframe     =   int(argv[3])
thr        = float(argv[4]) * u.AngstromToBohr
name_1     =       argv[5]
n_1        =   int(argv[6])
a_c        =       argv[7].split(',')
if len(argv)>8 : name_2     =     argv[8]
else:            name_2     = 'water'
if len(argv)>9 : n_2        = int(argv[9])
else:            n_2        = 3 # water as default
if len(argv)>10: a_s        =     argv[10].split(',')
else:            a_s        = ['O','H','H']

natoms  = read_xtc_natoms(trajectory)
nsmol   = (natoms-n_1)/n_2
assert (natoms-n_1)%n_2==0, 'Error in atom numbers: Total No: %5d does not contain integer number of moelcules!'
frame = zeros((natoms,DIM),dtype=float32)
box = zeros((DIM,DIM),dtype=float32)
XTC = xdrfile_open(trajectory,'r')

sym_c  = [ 'A%02i%s' % (x+1,a_c[x]) for x in range(len(a_c)) ]
sym_s  = [ 'A%02i%s' % (x+1,a_s[x]) for x in range(len(a_s)) ]
file_c = os.environ['SLV_PATH'] + '/frg/%s/%s.efp' % (name_1,name_1)
file_s = os.environ['SLV_PATH'] + '/frg/%s/%s.efp' % (name_2,name_2)

o  = open(file_c); par_c = o.read(); o.close()
o  = open(file_s); par_s = o.read(); o.close()

class Templ(Template): delimiter='@'
t_c = Templ(t_c); t_s = Templ(t_s)

def get_cog(r1):
    """calculate center of geometry"""
    cog = sum(r1,axis=0)/float(len(r1))
    return cog

def get_d(r1,r2):
    """calculate distance between r1 and r2 points"""
    d = msqrt(sum((r1-r2)*(r1-r2)))
    return d

def write(i,r_c,a_c,solvent_mols,a_s):
    """write xyz file and GAMESS inp file for i-th cluster"""
    global t_c, t_s
    soltxt = ''
    xyz = open('cluster-%03i.xyz' % i,'w') 
    inp = open('cluster-%03i.inp' % i,'w')
    #
    log = '%3d\n\n' % (len(a_c) + len(solvent_mols)*len(a_s))
    # write solute
    dat = ''
    for i in range(len(r_c)):
        log+=  '%2s'      %       a_c[i]
        log+= ' %14.6f'*3 % tuple(r_c[i])
        log+= '\n'
        #
        dat+=  '%s'       % sym_c[i]
        dat+= ' %14.6f'*3 % tuple(r_c[i])
        dat+=  '\n'
    # write solvents
    for sol in solvent_mols:
        txt = ''
        for i in range(len(a_s)):
            log+=  '%2s'      %       a_s[i]
            log+= ' %14.6f'*3 % tuple(sol[i])
            log+= '\n'
            #
            txt+=  '%s'       % sym_s[i]
            txt+= ' %14.6f'*3 % tuple(sol[i])
            txt+=  '\n'
        soltxt += t_s.substitute(SOLVENT=name_2.upper(),COORD=txt)
    log+= '\n'
    xyz.write(log)
    inp.write(t_c.substitute(SOLUTE=name_1.upper(),SOLVENT=name_2.upper(),
                             COORD=dat,            SCOORD=soltxt,
                             PARC=par_c,           PARS=par_s))
    xyz.close()
    inp.close()
    return


# 1. Pick the clusters
#

print " Picking clusters ..."
I= 0
for i in range(nframes):
    solvent_mols = list()
    #
    status, step, time, prec = read_xtc(XTC,box,frame)
    if not (i+1)%dframe:
       print " * Reading frame %10i"%(i+1),
       frame *= u.NanometerToAngstrom
       r_c = frame[:n_1]
       com_c = get_cog(r_c)
       #
       for n in range(nsmol):                   
           s_c = frame[n_1+n*n_2:n_1+(n+1)*n_2]
           com_s = get_cog(s_c)
           d = get_d(com_s,com_c)
           if d<=thr: solvent_mols.append(s_c)
       #
       print " no of solvent molecules: %3d" % len(solvent_mols)
       I+=1
       write(I,r_c,a_c,solvent_mols,a_s)

xdrfile_close(XTC) 
print " Congratulations! %4d clusters were picked and saved!\n" % I

# 2. Generate GAMESS EFP optimization input files
#




