#!/bin/bash
gnuplot plot-dq.gpl

for graph in nma-dq ; do
    epstopdf $graph-inc.eps
    pdflatex $graph.tex
    evince   $graph.pdf
    pdftops -eps $graph.pdf
    #pdf2svg  $graph.pdf $graph.svg
done
